project = 'Lua-Ext'
description = 'Extension libraries for the Lua programming language'
full_description = 'This library provides a collection of helpful functions for the Lua programming language.  Many of these functions are inspired by similar ones found in languages such as Ruby or Python.  The intent is to provide commonly-used helper functions at a low level of complexity.  Suggestions are always welcome, so feel free to [contact me](https://twitter.com/andrew_dunham).'
format = 'discount'
file = {'src'}
